name: testflutterapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #redux
  redux: ^3.0.0
  flutter_redux: ^0.5.0

  # firebase
  firebase_core: ^0.4.0
  firebase_database: ^3.0.5

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

